CREATE TABLE USUARIO(
ID INT PRIMARY KEY IDENTITY,
NOME VARCHAR(80) NOT NULL,
EMAIL VARCHAR(80) NOT NULL,
SENHA VARCHAR(10) NOT NULL,
FLAG_ATIVO VARCHAR(1) NOT NULL,
FLAG_NIVEL VARCHAR(1) NOT NULL,
DT_CADASTRO DATETIME
);
INSERT INTO USUARIO VALUES('Salumão Barbosa da Costa','salubcosta@gmail.com','ulas','S','3',GETDATE())